pipeline:
    clone:
        image: plugins/git
        tags: true
    test:
        image: node:7-alpine
        commands:
            - apk --update add git
            - npm i --quiet
            - npm t
    build:
        image: node:7-alpine
        commands:
            - npm run build
